POST {{host}}/user/signIn
Content-Type: application/json

{
  "email": "pascal@butterbach.org",
  "password": "the-password"
}
> {%
     client.global.set("access_token", response.body["access_token"]);
     client.global.set("refresh_token", response.body["refresh_token"]);
  %}

###
GET {{host}}/image/
Authorization: Bearer {{access_token}}

###
GET {{host}}/image/19
Authorization: Bearer {{access_token}}


###
DELETE {{host}}/image/26
Authorization: Bearer {{access_token}}


###
POST {{host}}/image/
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="8.jpg"


< C:\Users\Butti\Desktop\IMAGE-SERVICE-TEST-IMAGES\8.jpg
--WebAppBoundary--

###
POST {{host}}/image/
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2.png"


< C:\Users\Butti\Desktop\IMAGE-SERVICE-TEST-IMAGES\2.png
--WebAppBoundary--

###
POST {{host}}/image/
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="6.gif"


< C:\Users\Butti\Desktop\IMAGE-SERVICE-TEST-IMAGES\6.gif
--WebAppBoundary--

<> 2021-08-24T122058.200.json



